refactor: update presentation-exchange impl
trustbloc/edge-agent pull request #694
Opened 2021-03-13 03:03 UTC by llorllale

Signed-off-by: George Aristy <george.aristy@securekey.com>

2021-03-13 07:46 UTC, fqutishat approved these changes

2021-03-15 10:29 UTC, fqutishat requested changes
let's wait until we complete release for 0.1.6

2021-03-16 08:37 UTC, fqutishat approved these changes

2021-03-16 13:28 UTC, rolsonquadras approved these changes

2021-03-16 13:28 UTC, merged